### ISSUE TITLE
Text is Does not hided

### ISSUE THREAD

**Issue by DevHypers** [seeratawan01/fullview.js#3]
my code is here
```<section class="page-content" id="fullview">
        <div class="page main-img">
            <div class="main-title">
                <span class="text-left">Text</span>
                <span class="text-right">Text</span>
            </div>
        </div>
        <div class="page">
            1
        </div>
        <div class="page">
            1
        </div>
    </section>`

if i go next page, text is not hided

**Comment by DevHypers** [comment]
++ this is my css
    .main-title > .text-right {
        float: right;
        margin-right: 4.5%;
        font-size: 4.2vw;
    }    

    .main-title > .text-left {
        float: left;
        margin-left: 1%;
        font-size: 4.2vw;
    }

**Comment by seeratawan01** [comment]
can you showcase your snippet on [https://jsfiddle.net/](https://jsfiddle.net/,) so i could check it

**Comment by seeratawan01** [comment]
Closing the issue
